// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1h4JXXt9WIuytnUBczRDBnV2_OrBIlTg',
    appId: '1:547627529035:web:a376c79404cecc3f32eece',
    messagingSenderId: '547627529035',
    projectId: 'lumi-list-project-4d802',
    authDomain: 'lumi-list-project-4d802.firebaseapp.com',
    storageBucket: 'lumi-list-project-4d802.firebasestorage.app',
    measurementId: 'G-FMV3EFJ1JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_oUg565JUFiECn1xugQwGFvnDbz9mVng',
    appId: '1:547627529035:android:490b53d880ab62bf32eece',
    messagingSenderId: '547627529035',
    projectId: 'lumi-list-project-4d802',
    storageBucket: 'lumi-list-project-4d802.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfKcSNiPHIagMWdg9ge5OFhXqJPrtxLR8',
    appId: '1:547627529035:ios:290f3b7bc9f12cf032eece',
    messagingSenderId: '547627529035',
    projectId: 'lumi-list-project-4d802',
    storageBucket: 'lumi-list-project-4d802.firebasestorage.app',
    iosBundleId: 'com.example.lumiList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfKcSNiPHIagMWdg9ge5OFhXqJPrtxLR8',
    appId: '1:547627529035:ios:290f3b7bc9f12cf032eece',
    messagingSenderId: '547627529035',
    projectId: 'lumi-list-project-4d802',
    storageBucket: 'lumi-list-project-4d802.firebasestorage.app',
    iosBundleId: 'com.example.lumiList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1h4JXXt9WIuytnUBczRDBnV2_OrBIlTg',
    appId: '1:547627529035:web:70d6316e1e8ef0c832eece',
    messagingSenderId: '547627529035',
    projectId: 'lumi-list-project-4d802',
    authDomain: 'lumi-list-project-4d802.firebaseapp.com',
    storageBucket: 'lumi-list-project-4d802.firebasestorage.app',
    measurementId: 'G-F1B53CC6PD',
  );

}