// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYMv5P7srmjFMfQ_VIv9wxG9JLQwMiPlU',
    appId: '1:390786832651:web:517eb49b058c9ca3db6a0e',
    messagingSenderId: '390786832651',
    projectId: 'lumilist-c9c1e',
    authDomain: 'lumilist-c9c1e.firebaseapp.com',
    storageBucket: 'lumilist-c9c1e.firebasestorage.app',
    measurementId: 'G-JVZHN0YENF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiDmj8hGV7b3OIkIuHWmnBEDVmD2CEDm0',
    appId: '1:390786832651:android:edd48301b40b45f4db6a0e',
    messagingSenderId: '390786832651',
    projectId: 'lumilist-c9c1e',
    storageBucket: 'lumilist-c9c1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEUmWqpPgmQbnI0_jbpJXdpccUWJdycB4',
    appId: '1:390786832651:ios:019991154500a3e4db6a0e',
    messagingSenderId: '390786832651',
    projectId: 'lumilist-c9c1e',
    storageBucket: 'lumilist-c9c1e.firebasestorage.app',
    iosBundleId: 'com.example.lumiList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEUmWqpPgmQbnI0_jbpJXdpccUWJdycB4',
    appId: '1:390786832651:ios:019991154500a3e4db6a0e',
    messagingSenderId: '390786832651',
    projectId: 'lumilist-c9c1e',
    storageBucket: 'lumilist-c9c1e.firebasestorage.app',
    iosBundleId: 'com.example.lumiList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYMv5P7srmjFMfQ_VIv9wxG9JLQwMiPlU',
    appId: '1:390786832651:web:d031028303c8a1d8db6a0e',
    messagingSenderId: '390786832651',
    projectId: 'lumilist-c9c1e',
    authDomain: 'lumilist-c9c1e.firebaseapp.com',
    storageBucket: 'lumilist-c9c1e.firebasestorage.app',
    measurementId: 'G-9JB22JZWYY',
  );
}
